using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "CC0022:Should dispose object", Justification = "<Pending>", Scope = "member", Target = "~P:dotNetTips.Utility.Standard.AppLogging.LoggerFactory")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0033:Dispose Fields Properly", Justification = "<Pending>", Scope = "member", Target = "~F:dotNetTips.Utility.Standard.Cache.InMemoryCache._cache")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "DE0006:API is deprecated", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.App.GetEnvironmentVariables~System.Collections.Immutable.IImmutableDictionary{System.String,System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "PC001:API not supported on all platforms", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.IO.DirectoryHelper.LoadOneDriveFolders~System.Collections.Generic.IEnumerable{dotNetTips.Utility.Standard.IO.OneDriveFolder}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "PC001:API not supported on all platforms", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Win32.RegistryHelper.GetCurrentUserRegistryKey(System.String)~Microsoft.Win32.RegistryKey")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0006:Use foreach", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.IO.DirectoryHelper.CopyDirectory(System.String,System.String,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.IO.DirectoryHelper.CopyDirectory(System.String,System.String,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0004:Catch block cannot be empty", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.IO.FileHelper.MoveFile(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0004:Catch block cannot be empty", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.IO.FileHelper.MoveDirectory(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0004:Catch block cannot be empty", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.IO.DirectoryHelper.MoveDirectory(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0004:Catch block cannot be empty", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.IO.DirectoryHelper.DeleteDirectory(System.String)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.ArgumentInvalidException.#ctor")]
[assembly: SuppressMessage("Security", "CA5350:Do Not Use Weak Cryptographic Algorithms", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Security.EncryptionHelper.TripleDESDecrypt(System.Byte[],System.Byte[],System.Byte[])~System.String")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.IO.DirectoryHelper.DeleteDirectoryAsync(System.IO.DirectoryInfo)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:dotNetTips.Utility.Standard.Cache.InMemoryCache.Count")]
[assembly: SuppressMessage("Reliability", "CA2008:Do not create tasks without passing a TaskScheduler", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.IO.DirectoryHelper.DeleteDirectoryAsync(System.IO.DirectoryInfo)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.IO.FileHelper.UnGZipAsync(System.String,System.String,System.Boolean)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.IO.FileProcessor.CopyFiles(System.Collections.Generic.IEnumerable{System.IO.FileInfo},System.IO.DirectoryInfo)~System.Int32")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.IO.FileProcessor.CopyFiles(System.Collections.Generic.IEnumerable{System.IO.FileInfo},System.IO.DirectoryInfo)~System.Int32")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.OOP.Encapsulation.TryValidateParam(System.Enum,System.String,System.String)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Xml.XmlHelper.DeserializeFromXmlFile``1(System.String)~``0")]
[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Xml.XmlHelper.Serialize(System.Object)~System.String")]
[assembly: SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "<Pending>", Scope = "type", Target = "~T:dotNetTips.Utility.Standard.Collections.Generic.FastSortedList`1")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "type", Target = "~T:dotNetTips.Tips.Utility.Standard.EnvironmentKey")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.IO.FileHelper.DownloadFileFromWebAndUnzipAsync(System.Uri,System.String)~System.Threading.Tasks.Task")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Collections.Generic.Concurrent.ConcurrentHashSet`1.System#Collections#Generic#ICollection<T>#CopyTo(`0[],System.Int32)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Xml.XmlHelper.Serialize(System.Object)~System.String")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Serialization.JsonSerializer.Serialize(System.Object)~System.String")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.TypeHelper.FindDerivedTypes(System.String,System.IO.SearchOption,System.Type,System.Boolean)~System.Collections.Generic.IEnumerable{System.Type}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.TypeHelper.GetInstanceHashCode(System.Object)~System.Int32")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.TypeHelper.FindDerivedTypes(System.AppDomain,System.Type,System.Boolean)~System.Collections.Generic.IEnumerable{System.Type}")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Xml.XmlHelper.SerializeToXmlFile(System.Object,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.ArgumentReadOnlyException.#ctor")]
[assembly: SuppressMessage("Naming", "CA1724:Type names should not match namespaces", Justification = "<Pending>", Scope = "type", Target = "~T:dotNetTips.Utility.Standard.Services")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1010:Collections should implement generic interface", Justification = "<Pending>", Scope = "type", Target = "~T:dotNetTips.Utility.Standard.Collections.DistinctBlockingCollection`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Serialization.JsonSerializer.Serialize(System.Object)~System.String")]
[assembly: SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~P:dotNetTips.Utility.Standard.Singleton`1.Instance")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.TypeHelper.FindDerivedTypes(System.String,System.IO.SearchOption,System.Type,System.Boolean)~System.Collections.Generic.IEnumerable{System.Type}")]
[assembly: SuppressMessage("Security", "CA5369:Use XmlReader For Deserialize", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Xml.XmlHelper.Deserialize``1(System.String)~``0")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1724:Type names should not match namespaces", Justification = "<Pending>", Scope = "type", Target = "~T:dotNetTips.Utility.Standard.Enumeration")]