
// ***********************************************************************
// Assembly         : dotNetTips.Utility.Standard.Extensions
// Author           : David McCarter
// Created          : 09-28-2018
//
// Last Modified By : David McCarter
// Last Modified On : 03-03-2019
// ***********************************************************************
// <copyright file="GlobalSuppressions.cs" company="David McCarter - dotNetTips.com">
//     McCarter Consulting (David McCarter)
// </copyright>
// <summary></summary>
// ***********************************************************************

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CC0003:Your catch should include an Exception", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ObjectExtensions.TryDispose(System.IDisposable,System.Boolean)")]
[assembly: SuppressMessage("Usage", "PC001:API not supported on all platforms", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.RegistryExtensions.GetSubKey(Microsoft.Win32.RegistryKey,System.String)~Microsoft.Win32.RegistryKey")]

[assembly: SuppressMessage("Usage", "PC001:API not supported on all platforms", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.RegistryExtensions.GetValue``1(Microsoft.Win32.RegistryKey,System.String)~``0")]

[assembly: SuppressMessage("Usage", "DE0004:API is deprecated", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.WebClientExtensions.ConvertFrom``1(System.Net.WebClient,System.String)~``0")]
[assembly: SuppressMessage("Design", "CC0003:Your catch should include an Exception", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ObjectExtensions.TryDispose(IDisposable,System.Boolean)")]
[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ObjectExtensions.DisposeFields(System.IDisposable)")]
[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ObjectExtensions.HasProperty(System.Object,System.String)~System.Boolean")]
[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ObjectExtensions.TryDispose(System.IDisposable,System.Boolean)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.CollectionExtensions.AddIfNotExists``1(System.Collections.Generic.ICollection{``0},``0)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.CollectionExtensions.AddRange``1(System.Collections.Generic.ICollection{``0},System.Collections.Generic.IEnumerable{``0},System.Boolean)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.CollectionExtensions.AddRange``3(System.Collections.Generic.IDictionary{``1,``2},System.Collections.Generic.IEnumerable{``0},System.Func{``0,``1},System.Func{``0,``2})")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.CollectionExtensions.FromDelimitedString(System.String,System.Char)~System.Collections.Generic.IEnumerable{System.String}")]
[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ObjectExtensions.IsNotNull(System.Object)~System.Boolean")]

[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ExceptionExtensions.FromHierarchy``1(``0,System.Func{``0,``0},System.Func{``0,System.Boolean})~System.Collections.Generic.IEnumerable{``0}")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ColorExtensions.Average(System.Collections.Generic.IEnumerable{System.Drawing.Color})~System.Drawing.Color")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.CollectionExtensions.FastAny``1(System.Collections.Generic.IEnumerable{``0},System.Func{``0,System.Boolean})~System.Boolean")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.CollectionExtensions.FirstOrNull``1(System.Collections.Generic.IEnumerable{``0},System.Func{``0,System.Boolean})~System.Nullable{``0}")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.CollectionExtensions.HasItems``1(System.Collections.Generic.List{``0},System.Predicate{``0})~System.Boolean")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.CollectionExtensions.Page``1(System.Collections.Generic.IEnumerable{``0},System.Int32)~System.Collections.Generic.IEnumerable{System.Collections.Generic.IEnumerable{``0}}")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.CollectionExtensions.ToDelimitedString``1(System.Collections.Generic.IEnumerable{``0},System.Char)~System.String")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ColorExtensions.Average(System.Collections.Generic.IEnumerable{System.Drawing.Color})~System.Drawing.Color")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.EnumExtensions.As``1(System.Enum)~``0")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.EnumExtensions.GetDescription(System.Enum)~System.String")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.EnumExtensions.GetDescriptionInternal``1(System.Object)~dotNetTips.Utility.Standard.Extensions.EnumItem{``0}")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.EnumExtensions.Parse``1(System.String)~``0")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ExceptionExtensions.FromHierarchy``1(``0,System.Func{``0,``0},System.Func{``0,System.Boolean})~System.Collections.Generic.IEnumerable{``0}")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.HttpRequestExtensions.GetRawBodyBytesAsync(Microsoft.AspNetCore.Http.HttpRequest)~System.Threading.Tasks.Task{System.Byte[]}")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ObjectExtensions.DisposeFields(System.IDisposable)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ObjectExtensions.InitializeFields(System.Object)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.StringExtensions.Concat(System.String,System.String,System.Boolean,System.String[])~System.String")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.StringExtensions.ContainsAny(System.String,System.String[])~System.Boolean")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.StringExtensions.ToTrimmedString(System.String)~System.String")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.TypeExtensions.Max``1(``0,``0)~``0")]
[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ObjectExtensions.Clone``1(System.Object)~``0")]
[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ObjectExtensions.InitializeFields(System.Object)")]
[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ObjectExtensions.IsNull(System.Object)~System.Boolean")]
[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ObjectExtensions.ToJson(System.Object)~System.String")]
[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ObjectExtensions.ToJsonFile(System.Object,System.String)")]
[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ObjectExtensions.TryDispose(System.IDisposable)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ObjectExtensions.ToJsonFile(System.Object,System.String)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.WebClientExtensions.ConvertFrom``1(System.Net.WebClient,System.String)~``0")]
[assembly: SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.WebClientExtensions.ConvertFrom``1(System.Net.WebClient,System.String)~``0")]

[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.DateTimeExtensions.GetNext(System.DateTime,System.DayOfWeek)~System.DateTime")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.DateTimeExtensions.ToFriendlyDateString(System.DateTime)~System.String")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.HttpRequestExtensions.TryGetBody``1(Microsoft.AspNetCore.Http.HttpRequest,``0@)~System.Boolean")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.HttpRequestExtensions.TryGetBody(Microsoft.AspNetCore.Http.HttpRequest,System.Byte[]@)~System.Boolean")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.DateTimeExtensions.ToFormattedString(System.DateTime,dotNetTips.Utility.Standard.Extensions.DateTimeFormat)~System.String")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:dotNetTips.Utility.Standard.Extensions.ObjectExtensions.ToJson(System.Object)~System.String")]
