// ***********************************************************************
// Assembly         : dotNetTips.Utility.Standard.Extensions
// Author           : David McCarter
// Created          : 02-14-2018
//
// Last Modified By : David McCarter
// Last Modified On : 03-03-2019
// ***********************************************************************
// <copyright file="Resources.Designer.cs" company="dotNetTips.com - David McCarter">
//     McCarter Consulting (David McCarter)
// </copyright>
// <summary></summary>
// ***********************************************************************

namespace dotNetTips.Utility.Standard.Extensions.Properties
{
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        /// <summary>
        /// The resource man
        /// </summary>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        /// The resource culture
        /// </summary>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Initializes a new instance of the <see cref="Resources" /> class.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        /// <value>The resource manager.</value>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dotNetTips.Utility.Standard.Extensions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        /// <value>The culture.</value>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Bytes.
        /// </summary>
        /// <value>The bytes.</value>
        internal static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to {0} cannot be of type Exception. Use a more specific exception from the framework or a custom Exception inheriting type Exception (only)..
        /// </summary>
        /// <value>The cannot be of type exception.</value>
        internal static string CannotBeOfTypeException {
            get {
                return ResourceManager.GetString("CannotBeOfTypeException", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Collection is null or has no items..
        /// </summary>
        /// <value>The collection is null or has no items.</value>
        internal static string CollectionIsNullOrHasNoItems {
            get {
                return ResourceManager.GetString("CollectionIsNullOrHasNoItems", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Collection size is not valid..
        /// </summary>
        /// <value>The collection size is not valid.</value>
        internal static string CollectionSizeIsNotValid {
            get {
                return ResourceManager.GetString("CollectionSizeIsNotValid", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Exception cannot be null..
        /// </summary>
        /// <value>The exception cannot be null.</value>
        internal static string ExceptionCannotBeNull {
            get {
                return ResourceManager.GetString("ExceptionCannotBeNull", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to File not found..
        /// </summary>
        /// <value>The file not found.</value>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to File size is invalid..
        /// </summary>
        /// <value>The file size is invalid.</value>
        internal static string FileSizeIsInvalid {
            get {
                return ResourceManager.GetString("FileSizeIsInvalid", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Folder not found..
        /// </summary>
        /// <value>The folder not found.</value>
        internal static string FolderNotFound {
            get {
                return ResourceManager.GetString("FolderNotFound", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to GB.
        /// </summary>
        /// <value>The gb.</value>
        internal static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Guid is Empth..
        /// </summary>
        /// <value>The unique identifier is empty.</value>
        internal static string GuidIsEmpty {
            get {
                return ResourceManager.GetString("GuidIsEmpty", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Invalid type..
        /// </summary>
        /// <value>The type of the invalid.</value>
        internal static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to KB.
        /// </summary>
        /// <value>The kb.</value>
        internal static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Length must be greater than 0..
        /// </summary>
        /// <value>The length must be greater than0.</value>
        internal static string LengthMustBeGreaterThan0 {
            get {
                return ResourceManager.GetString("LengthMustBeGreaterThan0", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to MB.
        /// </summary>
        /// <value>The mb.</value>
        internal static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Parameter is invalid. .
        /// </summary>
        /// <value>The parameter is invalid.</value>
        internal static string ParameterIsInvalid {
            get {
                return ResourceManager.GetString("ParameterIsInvalid", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Strings do not match..
        /// </summary>
        /// <value>The string does not match.</value>
        internal static string StringDoesNotMatch {
            get {
                return ResourceManager.GetString("StringDoesNotMatch", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to String does not matach maximum length..
        /// </summary>
        /// <value>The maximum length of the string does not match.</value>
        internal static string StringDoesNotMatchMaximumLength {
            get {
                return ResourceManager.GetString("StringDoesNotMatchMaximumLength", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to String does not match minimum length..
        /// </summary>
        /// <value>The minimum length of the string does not match.</value>
        internal static string StringDoesNotMatchMinimumLength {
            get {
                return ResourceManager.GetString("StringDoesNotMatchMinimumLength", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to String is empty..
        /// </summary>
        /// <value>The string is empty.</value>
        internal static string StringIsEmpty {
            get {
                return ResourceManager.GetString("StringIsEmpty", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to String is not valid..
        /// </summary>
        /// <value>The string is not valid.</value>
        internal static string StringIsNotValid {
            get {
                return ResourceManager.GetString("StringIsNotValid", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to The values are not defined in the enum..
        /// </summary>
        /// <value>The value is not defined in the enumeration.</value>
        internal static string TheValueIsNotDefinedInTheEnumeration {
            get {
                return ResourceManager.GetString("TheValueIsNotDefinedInTheEnumeration", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Value is invalid..
        /// </summary>
        /// <value>The value is invalid.</value>
        internal static string ValueIsInvalid {
            get {
                return ResourceManager.GetString("ValueIsInvalid", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Yesterday.
        /// </summary>
        /// <value>The yesterday.</value>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
